import ConvexClientProvider from '@/components/convex-client-provider'
import '@liveblocks/react-ui/styles.css'
import '@liveblocks/react-tiptap/styles.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Script from 'next/script'
import { NuqsAdapter } from 'nuqs/adapters/next/app'
import './globals.css'
import { Toaster } from '@/components/ui/sonner'

const inter = Inter({
  subsets: ['latin'],
  weight: ['400'],
})

export const metadata: Metadata = {
  title: 'Docify',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Script
          data-organization-id="org_3FqBlQ3PWVtRUx3WMWWE2bj8u2J"
          src="https://auxilium-widget.vercel.app/widget.js"
        />
        <Toaster position="top-right" />
        <NuqsAdapter>
          <ConvexClientProvider>{children}</ConvexClientProvider>
        </NuqsAdapter>
      </body>
    </html>
  )
}
